### ISSUE TITLE
Add Meta Vault contracts to developer docs

### ISSUE THREAD

**Issue by dimsome** [mstable/metavaults#77]
## About

With the launch of the Meta Vault we should maintain good developer experience. https://developers.mstable.org/

## Acceptance Criteria

- [x] Add contract structure
- [x] Add generic 4626 page and link from other compatible contracts
- [x] Document non standard functions (from natspec)
- [x] Document Admin controls
- [x] Checklist from DeFiSafety  https://www.defisafety.com/app/pqrs/377
- [x] Merge latest developer doc changes so they are public
